# The URL the site will be built for

# this variable has to be set but it is not used
# inside the templates (end in '/')
base_url = "https://robotmeetsranging.tech"

# When adapting the title, do not forget to also adjust base_url above
title = "Workshop on Robot Meets GNSS and Ranging for Seamless Autonomy" 
description = "Exploring Synergies and Challenges of Radio-based Ranging Technologies in Robotics"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = true
#highlight_theme = "cheerfully-light"

# Whether external links are to be opened in a new tab
external_links_target_blank = true

[extra]

navigation = [
    { name = "Home", target = "" },
    { name = "Motivation and Goal", target = "objective/" },
    { name = "Workshop Content", target = "workshop_content/" },
    #{ name = "Call for Abstract", target = "abstract/" },
    #{ name = "How to join", target = "join/" },
    #{ name = "Requirements", target = "requirements/" },
    #{ name = "Q&A", target = "questions/" },
    #{ name = "Code of conduct", target = "code-of-conduct/" },
    #{ name = "Contact", target = "communication/" }
]

twitter_image = "https://github.com/hz658832/RobotMeetGNSS/blob/main/content/header_tighter.png"

# plausible.io analytics
plausible = { src = "https://plausible.cs.aalto.fi/js/script.js", domain = "coderefinery.github.io", github_ref = "refs/heads/main" }


# you can place multiple logos like this
# the image file(s) need to be placed in content/logos
logos = [
#   { alt_text = "CodeRefinery logo", target_url = "https://coderefinery.org/", image = "coderefinery.png" },
    { alt_text = "RobotMeetsGNSS logo", target_url = "https://robotmeetsranging.tech/", image = "header_tighter_icon.png" }
]

# adapt this
registration_link = "https://example.org"
source_repo = "https://github.com/hz658832/RobotMeetGNSS"
how_to_join_video = "https://youtu.be/QUAZELOioUY"

# uncomment as soon as registration opens
# registration_is_open = true

# uncomment as soon as registration closes
# registration_is_closed = true
